# Generated by Django 5.1.6 on 2025-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                ("amount", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
